# Generated by Django 5.0.2 on 2024-03-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forumai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Naudotojai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=255)),
                ('pavarde', models.CharField(max_length=255)),
                ('telefonas', models.CharField(max_length=255)),
                ('el_pastas', models.CharField(max_length=255)),
                ('gimimo_data', models.DateField()),
                ('usename', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kk', models.CharField(max_length=255)),
                ('kalorijos', models.IntegerField()),
                ('pavadinimas', models.CharField(max_length=255)),
                ('fenilalaninas', models.IntegerField()),
                ('aprasas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Irasai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstas', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('fk_Forumasid_Forumas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.forumai')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Kraujo_tyrimai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fenilalaninas', models.IntegerField()),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Komentarai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekstas', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('fk_Irasasid_Irasas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.irasai')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Naudotojo_receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
        migrations.CreateModel(
            name='Recepto_produktai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Produktasid_Produktas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgiarasciai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diena', models.IntegerField()),
                ('bendras_fenilalaninas', models.IntegerField()),
                ('data', models.DateField()),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgymai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipas', models.CharField(max_length=255)),
                ('fk_Valgiarastisid_Valgiarastis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgiarasciai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgomas_produktas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Produktasid_Produktas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
                ('fk_Valgymasid_Valgymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgymai')),
            ],
        ),
        migrations.CreateModel(
            name='Valgymo_receptas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
                ('fk_Valgymasid_Valgymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.valgymai')),
            ],
        ),
        migrations.CreateModel(
            name='Megstamiausi_receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Receptai')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Naudotojai')),
            ],
        ),
    ]
