# Generated by Django 5.0.2 on 2024-03-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_forumai_naudotojai_receptai_irasai_kraujo_tyrimai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptai',
            name='kk',
        ),
    ]
