# Generated by Django 4.2.7 on 2024-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_recepto_produktai_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='gramai', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='blue', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='homePhenylalanine',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='homeWeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(default='gramai', max_length=255),
            preserve_default=False,
        ),
    ]
