# Generated by Django 5.0.3 on 2024-04-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_recepto_produktai_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mėgstamiausi_receptai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Naudotojasid_Naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naudotojai')),
                ('fk_Receptasid_Receptas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.receptai')),
            ],
        ),
    ]
