# Generated by Django 5.0.3 on 2024-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_mėgstamiausi_receptai'),
        ('homepage', '0016_valgymo_receptas_kiekis'),
    ]

    operations = [
    ]
