# Generated by Django 5.0.3 on 2024-04-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_merge_20240418_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mėgstamiausi_receptai',
            new_name='Megstamiausi_receptai',
        ),
    ]
