# Generated by Django 4.2.7 on 2024-04-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_receptai_baltymai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pavadinimas',
        ),
    ]
