# Generated by Django 5.0.2 on 2024-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_valgiarasciai_bendras_baltymas_and_more'),
        ('homepage', '0024_irasai_category'),
    ]

    operations = [
    ]
