# Generated by Django 5.0.2 on 2024-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_merge_20240502_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irasai',
            name='category',
            field=models.CharField(default='Daktarui', max_length=50),
        ),
        migrations.AlterField(
            model_name='irasai',
            name='tekstas',
            field=models.CharField(max_length=2555),
        ),
    ]
