# Generated by Django 5.0.2 on 2024-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_receptai_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptai',
            name='fenilalaninas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receptai',
            name='kalorijos',
            field=models.FloatField(),
        ),
    ]
