# Generated by Django 5.0.2 on 2024-03-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_delete_todoitem_naudotojai_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naudotojai',
            old_name='usename',
            new_name='username',
        ),
    ]
