# Generated by Django 5.0.2 on 2024-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_naudotojai_options_alter_naudotojai_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naudotojai',
            options={},
        ),
        migrations.AlterModelManagers(
            name='naudotojai',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='email',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='naudotojai',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='naudotojai',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
