# Generated by Django 5.0.2 on 2024-03-21 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_naudotojai_options_alter_naudotojai_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naudotojai',
            name='password',
        ),
        migrations.RemoveField(
            model_name='naudotojai',
            name='username',
        ),
        migrations.AddField(
            model_name='naudotojai',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
