# Generated by Django 4.2.7 on 2024-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_product_category_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='homePhenylalanine',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='phenylalanine',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
