# Generated by Django 4.2.7 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_product_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='valgomas_produktas',
            name='kiekis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
