# Generated by Django 4.2.7 on 2024-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_valgiarasciai_bendras_baltymas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptai',
            name='baltymai',
            field=models.FloatField(default=0.0),
        ),
    ]
