# Generated by Django 4.2.7 on 2024-04-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_rename_name_product_pavadinimas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pavadinimas',
            new_name='name',
        ),
    ]
