# Generated by Django 5.0.2 on 2024-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_merge_20240422_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='irasai',
            name='category',
            field=models.CharField(default='Klausimai daktarui', max_length=50),
        ),
    ]
